spring:
  application:
    name: simpleJWT1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authPracDb
    username: karan
    password: karan@123
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

server:
  port: 8080

app:
  jwt:
    jwt-secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

logging:
  level:
    root: info
